### ISSUE TITLE
国内服务器 proxy 到 GitHub Pages 访问速度很慢

### ISSUE THREAD

**Issue by shen360** [geneasy/links#4]
国内服务器 proxy 到 GitHub Pages 访问速度很慢，有时甚至 timeout。
有什么好的解决方法吗？

**Comment by PipecraftNet** [comment]
不妨试试把项目部署到 Netlify, 然后 proxy 到 netlify。

访问 https://www.netlify.com/ ，用 GitHub 登录以后，几步操作就可以把 GitHub Pages 部署到 Netlify。
并且可以设置你想要的域名，比如这个项目设置了这个域名 https://geneasy-links.netlify.app/

然后 proxy 设置的地方把 `xxx.github.io` 改成 `xxx.netlify.app` 。

nginx 举例

```
location /links/ {
    proxy_pass      https://geneasy-links.netlify.app/;
    proxy_intercept_errors on;

    # allow GitHub to pass caching headers instead of using our own
    expires off;
    proxy_set_header   Host                   geneasy-links.netlify.app;
    proxy_set_header   X-Host                 geneasy-links.netlify.app;
}
```
